#!/bin/bash

ENV_DIR="env"

python3 -m venv $ENV_DIR
source $ENV_DIR/bin/activate

# Upgrade pip, setuptools, and wheel first
pip install --upgrade pip setuptools wheel

# Install dependencies
pip install -r requirements.txt

echo "Virtual environment setup complete and dependencies installed."
